name: Website

on:
  push:
    branches: ['main']
    tags: ['*']

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - name: Publish Github pages
        run: sbt docs/docusaurusPublishGhpages
        env:
          GIT_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}